[package]
name = "discord-ollama"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.3"
poise = "0.6.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
ollama-rs = "0.2.4"
